### ISSUE TITLE
MainWindow should cath close event and handle thread

### ISSUE THREAD

**Issue by stndart** [stndart/2d-velocity-pathfinding#1]
Exception in thread MainWindow::main_thread:
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sstnd\Documents\Projects\2d-speed-nav\gui\main_window.py", line 44, in main_thread
    self.main_view.update_frame(deltatime)
    ^^^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists

Happens once the window is closed.

**Comment by stndart** [comment]
closed in 4c92a254183a6ca56c1f0401a56623816ddd45ce
